#!/usr/bin/env python3

import os
import sys
import json

import click

from marketcl.dialogues import startup_check, make_game, parse_game_arg
from marketcl.items import Game

MARKETCL_PATH = os.path.expandvars("$HOME/.marketcl")

@click.command()
@click.option("--ls", "-l", is_flag=True, help="List holdings")
@click.option("--buy", "-b", is_flag=True, help="Buy a new stock")
@click.option("--sell", "-s", is_flag=True, help="Sell stock from your current portfolio")
@click.option("--game", "-g", "game_choice", type=click.Choice(["new", "ls", "switch", "rm"]),
              help="Start a new game, list ongoing games, switch games, or delete an existing game")
def main(ls, buy, sell, game_choice):
    if game_choice:
        parse_game_arg(game_choice, MARKETCL_PATH)
        sys.exit(0)

    game = Game(MARKETCL_PATH)

    if ls:
        game.print()
        sys.exit(0)

    if buy:
        game.buy()
        sys.exit(0)

    if sell:
        game.sell()
        sys.exit(0)

if __name__ == "__main__":
    startup_check(MARKETCL_PATH)
    main()
