#!/usr/bin/env python3

import os
import sys
import json

from marketcl.dialogues import startup_check, make_game, parse_game_arg
from marketcl.items import Game

MARKETCL_PATH = os.path.expandvars("$HOME/.marketcl")

def main(args):
    if args[1] == "game":
        if len(args) >= 3:
            parse_game_arg(args[2], MARKETCL_PATH)
        else:
            print("Game argument needs another option!")

    game = Game(MARKETCL_PATH)

    if args[1] in ["buy", "b"]:
        game.buy()
    elif args[1] in ["sell", "s"]:
        game.sell()
    elif args[1] in ["list", "ls", "l"]:
        game.print()

if __name__ == "__main__":
    startup_check(MARKETCL_PATH)
    main(sys.argv)
